locals {
  # Define the Airflow environment name
  airflow_environment_name = "Sec-Airflow"

  # Default team tag
  team_tag = "security-operations"

  # List of bucket names to be used as DAG outputs
  s3_bucket_names = {
    prod = []
  }

  # Bucket where airflow DAGS, plugins, and
  # requirements.txt are loaded from
  airflow_dags_s3_bucket_name = {
    prod = "airflow-data-prod"
  }

  # Default AWS VPC name to use for airflow
  airflow_vpc_name = {
    prod = "sec-vpc"
  }

  # Default AWS subnet IDs to use for airflow
  airflow_subnet_id_list = {
    prod = [
      "fake-subnet-0b323342346dfa",
      "fake-subnet-0b3233631965ca"
    ]
  }

  # Override default service tag for data buckets and SQS queues when enabled
  data_service_tag = "sec-data"

  # SSM root path for reading parameter store secrets
  # arn:aws:ssm:${region}:${account_id}:parameter/${ssm_parameter_path}/*
  ssm_parameter_path = "sec-airflow"

  # Enable SQS queues for all Airflow DAG output buckets
  sqs = {
    create = false
  }

  # Enable Kinesis subscriptions to Cloudwatch logs
  # for logs generated by Apache Airflow
  logstream = {
    create = false
  }
}
